### ISSUE TITLE
No secret Key hiding

### ISSUE THREAD

**Issue by Lashuk1729** [crespoter/djangotutorial_buggyversion#6]
https://github.com/crespoter/djangotutorial_buggyversion/blob/53e4837d6c4de466851c982c037ed11a61d0fc50/awesomesite/settings.py#L7

Respected Sir,
This line has its secret key exposed. This when used in production might lead to hacking by Sri Harsha Gajjavalli.
Please FFS put this in your Environment variables.
Yours caring Friend,
lashuk1729

**Comment by crespoter** [comment]
Thank you for your concerns about the tutorial website's security. But I assure you that you have nothing worry about. As mentioned by @SriHarshaGajavalli  we can currently avoid this issue, however free feel to reopen this issue when required.
