### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by Lashuk1729** [crespoter/djangotutorial_buggyversion#8]
Dear Contributors,

`requirements.txt` are an essential component of an python environment. These tell any programmer the required libraries needed run the repo. Please add these.

Regards,
lashuk1729

**Comment by SriHarshaGajavalli** [comment]
@Lashuk1729 

Well, currently this project doesn't need anything to be installed apart from django. it would be redundant if we create a requirements.txt file as of now.

@crespoter I hope close this issue now and can reopen when there is a need.

**Comment by crespoter** [comment]
Closing this issue.
